# Save as .codeclimate.yml (note leading .) in project root directory
languages:
  Ruby: false
  JavaScript: true
  PHP: true
  Python: false
exclude_paths:
  - "vendor/*"
engines:
  phpcodesniffer:
    enabled: true
    config:
      - custom_exclude_paths: "/vendor/*"
      - file_extensions: "php,inc,lib"
      - standard: "PSR1","PSR2"
