language: php

php:
  - 5.4

sudo: false

before_install:
  - phpenv config-add .travis.php.ini
  - composer self-update
  - if [ -f ~/composer/composer.phar ]; then mv ~/composer/composer.phar ./; else wget https://getcomposer.org/composer.phar; fi
  - mkdir -p ~/composer
  - cp composer.phar ~/composer/composer.phar

install:
  - php -d memory_limit=-1 ./composer.phar install --no-progress --prefer-dist

script: ./bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN=4a6c1ee790fc11bf750955c0f4dbfb8283404d734b1e2bf757a2e81c69045639 ./bin/test-reporter
