language: php

php:
  - 5.6
  - 7.0

sudo: false

cache:
  directories:
    - ~/.composer/cache

install:
  - composer self-update
  - export COMPOSER_ROOT_VERSION=dev-master
  - composer install --no-progress --prefer-dist

script: ./bin/phpunit

addons:
  code_climate:
    repo_token: 4a6c1ee790fc11bf750955c0f4dbfb8283404d734b1e2bf757a2e81c69045639 

after_script:
  - ./bin/test-reporter
